update HACS install script remove existing HACS direcorty before install

diff --git a/overlay/root/.plugin/bin/install-hacs b/overlay/root/.plugin/bin/install-hacs
--- a/overlay/root/.plugin/bin/install-hacs
+++ b/overlay/root/.plugin/bin/install-hacs
@@ -7,23 +7,23 @@
 
 # shellcheck disable=SC2154
 homeassistant_install_hacs() {
-  local _custom_components_ _hacs_ _zip_
-  _custom_components_="${1:-"${homeassistant_config_dir}"}/custom_components"
-  _hacs_="${_custom_components_}/hacs"
-  ## Check for existing directory. Fail if it's not empty, install if it does not exist
-  if [ -d "${_hacs_}" ] && [ -n "$(ls -A "${_hacs_}")" ]; then
-    echo -e "\nHACS is already installed: ${_hacs_}" ; err 1 "expecting empty directory"
-  elif [ ! -d "${_custom_components_}" ]; then
-    install -d -g "${homeassistant_group}" -m 775 -o "${homeassistant_user}" -- "${_custom_components_}"
+  local custom_components hacs zip
+  custom_components="${1:-"${homeassistant_config_dir}"}/custom_components"
+  hacs="${custom_components}/hacs"
+  if [ -d "${hacs}" ]; then
+    echo -e "\nHACS directory already exist, cleaning up..."
+    rm -R "${hacs}"
+  elif [ ! -d "${custom_components}" ]; then
+    install -d -g "${homeassistant_group}" -m 775 -o "${homeassistant_user}" -- "${custom_components}"
   fi
   ## Download hacs.zip to a tmp_file and test, then extract to final location.
-  _zip_="$(mktemp -t hacs)"
-  wget -O "${_zip_}" https://github.com/hacs/integration/releases/latest/download/hacs.zip
-  unzip -qt "${_zip_}" || { rm "${_zip_}" ; err 1 "failed to extract" ; }
-  unzip -d "${_hacs_}" "${_zip_}" \
-  && chown -R "${homeassistant_user}":"${homeassistant_group}" "${_hacs_}" \
+  zip="$(mktemp -t hacs)"
+  wget -O "${zip}" https://github.com/hacs/integration/releases/latest/download/hacs.zip
+  unzip -qt "${zip}" || { rm "${zip}" ; err 1 "failed to extract" ; }
+  unzip -d "${hacs}" "${zip}" \
+  && chown -R "${homeassistant_user}":"${homeassistant_group}" "${hacs}" \
   && echo -e "\nRemember to restart Home Assistant before you configure HACS\n https://hacs.xyz/docs/configuration/start \n"
-  rm "${_zip_}"
+  rm "${zip}"
 }
 
 homeassistant_install_hacs "${1}"
