11.2-RELEASE

diff --git a/overlay/usr/local/etc/rc.d/appdaemon b/overlay/usr/local/etc/rc.d/appdaemon
--- a/overlay/usr/local/etc/rc.d/appdaemon
+++ b/overlay/usr/local/etc/rc.d/appdaemon
@@ -1,28 +1,30 @@
 #!/bin/sh
-
+#
 # PROVIDE: appdaemon
 # REQUIRE: LOGIN
 # KEYWORD: shutdown
 #
-# appdaemon_enable:	Set to YES to enable the appdaemon service.
-#			Default: NO
-# appdaemon_user:	The user account used to run the appdaemon daemon.
-#			This is optional, however do not specifically set this to an
-#			empty string as this will cause the daemon to run as root.
-#			Default: USER_NAME
-# appdaemon_group:	The group account used to run the appdaemon daemon.
-#			This is optional, however do not specifically set this to an
-#			empty string as this will cause the daemon to run with group wheel.
-#			Default: USER_GROUP
-# appdaemon_config_dir:	Directory where appdaemon config is located.
-#			Default: ~/appdaemon/conf
+# appdaemon_enable: Set to YES to enable the appdaemon service.
+#		Default: NO
+# appdaemon_user: The user account used to run the appdaemon daemon.
+#		This is optional, however do not specifically set this to an
+#		empty string as this will cause the daemon to run as root.
+#		Default: hass
+# appdaemon_group: The group account used to run the appdaemon daemon.
+#		This is optional, however do not specifically set this to an
+#		empty string as this will cause the daemon to run with group wheel.
+#		Default: hass
+# appdaemon_config_dir: Directory where appdaemon config is located.
+#		Default: "/home/hass/appdaemon/conf"
+# appdaemon_venv: Directory where appdaemon virtualenv is located.
+#		Default: "/usr/local/share/appdaemon"
 #
-# copy this file to /usr/local/etc/rc.d/appdaemon 
-# chmod +x /usr/local/etc/rc.d/appdaemon
-#
-# sysrc appdaemon_enable=yes                # to enable
-# sysrc appdaemon_config_dir="~/appdaemon"  # to change
-# service appdaemon start                   # to start
+# -------------------------------------------------------
+# Copy this file to '/usr/local/etc/rc.d/appdaemon' 
+# `chmod +x /usr/local/etc/rc.d/appdaemon`
+# `sysrc appdaemon_enable=yes`
+# `service appdaemon start`
+# -------------------------------------------------------
 
 . /etc/rc.subr
 name=appdaemon
@@ -32,41 +34,73 @@ pidfile_child="/var/run/${name}.pid"
 pidfile="/var/run/${name}_daemon.pid"
 logfile="/var/log/${name}_daemon.log"
 
-load_rc_config ${name}
 : ${appdaemon_enable:="NO"}
 : ${appdaemon_user:="hass"}
 : ${appdaemon_group:="hass"}
 : ${appdaemon_config_dir:="/home/hass/appdaemon/conf"}
+: ${appdaemon_venv:="/srv/appdaemon"}
 
 command="/usr/sbin/daemon"
+extra_commands="restart test upgrade"
 
 start_precmd=${name}_precmd
-appdaemon_precmd()
-{
-        rc_flags="-f -o ${logfile} -P ${pidfile} -p ${pidfile_child} /srv/appdaemon/bin/appdaemon -c ${appdaemon_config_dir} ${rc_flags}"
-        
-    if [ ! -e "${pidfile_child}" ]; then
-            install -g ${appdaemon_group} -o ${appdaemon_user} -- /dev/null "${pidfile_child}";
-    fi
-
-    if [ ! -e "${pidfile}" ]; then
-            install -g ${appdaemon_group} -o ${appdaemon_user} -- /dev/null "${pidfile}";
-    fi
-
-    if [ ! -e "${logfile}" ]; then
-        install -g ${appdaemon_group} -o ${appdaemon_user} -- /dev/null "${logfile}";
-    fi
- 
+appdaemon_precmd() {
+    rc_flags="-f -o ${logfile} -P ${pidfile} -p ${pidfile_child} ${appdaemon_venv}/bin/appdaemon -c ${appdaemon_config_dir} ${rc_flags}"
+    [ ! -e "${pidfile_child}" ] && install -g ${appdaemon_group} -o ${appdaemon_user} -- /dev/null "${pidfile_child}"
+    [ ! -e "${pidfile}" ] && install -g ${appdaemon_group} -o ${appdaemon_user} -- /dev/null "${pidfile}"
+    [ ! -e "${logfile}" ] && rm -f -- "${logfile}"
+    install -g ${appdaemon_group} -o ${appdaemon_user} -- /dev/null "${logfile}"
     if [ ! -d "${appdaemon_config_dir}" ]; then
-        install -d -g ${appdaemon_group} -o ${appdaemon_user} -- "${appdaemon_config_dir}";
+      install -d -g ${appdaemon_group} -o ${appdaemon_user} -- "${appdaemon_config_dir}"
     fi
 }
 
 stop_postcmd=${name}_postcmd
-appdaemon_postcmd()
-{
+appdaemon_postcmd() {
     rm -f -- "${pidfile}"
     rm -f -- "${pidfile_child}"
 }
 
+restart_cmd="${name}_restart"
+appdaemon_restart() {
+    service ${name} stop
+    sleep 1
+    service ${name} start
+}
+
+upgrade_cmd="${name}_upgrade"
+appdaemon_upgrade() {
+    service ${name} stop
+    su ${appdaemon_user} -c '
+      source ${1}/bin/activate || exit 1
+      pip3 install --upgrade appdaemon
+      deactivate
+    ' _ ${appdaemon_venv} || exit 1
+    [ $? == 0 ] && service ${name} start
+}
+
+test_cmd="${name}_test"
+appdaemon_test() {
+    ## This function servers as a simple test command.
+    echo "TEST FUNCTION"
+
+    ## return 1 if "${appdaemon_venv}" does not exist
+    [ ! -d "${appdaemon_venv}" ] && echo -e " NO DIRECTORY: ${appdaemon_venv}\n" && exit 1
+
+    ## Switch users / activate virtualenv / run a command
+    su "${appdaemon_user}" -c '
+      source ${@}/bin/activate || exit 2
+      echo " $(python --version)" || exit 3
+      echo " Hass Configurator $(pip3 show appdaemon | grep Version | cut -d" " -f2)" || exit 4
+      deactivate
+    ' _ ${appdaemon_venv} || exit 1
+
+    local e=$?
+    ## Do something based on the value of e
+    [ $e == 2 ] && echo -e "Failed to activate virtualenv:\n ${appdaemon_venv}" || exit
+    [ $e == 3 ] && echo -e "Failed to get python version" || exit
+    [ $e == 4 ] && echo -e "${name} is not installed" || exit
+}
+
+load_rc_config ${name}
 run_rc_command "$1"
diff --git a/overlay/usr/local/etc/rc.d/configurator b/overlay/usr/local/etc/rc.d/configurator
--- a/overlay/usr/local/etc/rc.d/configurator
+++ b/overlay/usr/local/etc/rc.d/configurator
@@ -4,25 +4,33 @@
 # REQUIRE: LOGIN
 # KEYWORD: shutdown
 #
-# configurator_enable:	Set to YES to enable the configurator service.
-#			Default: NO
-# configurator_user:	The user account used to run the configurator daemon.
-#			This is optional, however do not specifically set this to an
-#			empty string as this will cause the daemon to run as root.
-#			Default: USER_NAME
-# configurator_group:	The group account used to run the configurator daemon.
-#			This is optional, however do not specifically set this to an
-#			empty string as this will cause the daemon to run with group wheel.
-#			Default: USER_GROUP
-# configurator_conf:	Hass-Configurator user settings
-#			Default: ~/configurator/configurator.conf
+# configurator_enable: Set to YES to enable the hass-configurator service.
+#		Default: NO
+# configurator_user: The user account used to run the hass-configurator daemon.
+#		This is optional, however do not specifically set this to an
+#		empty string as this will cause the daemon to run as root.
+#		Default: ${USER}
+# configurator_group: The group account used to run the hass-configurator daemon.
+#		This is optional, however do not specifically set this to an
+#		empty string as this will cause the daemon to run with group wheel.
+#		Default: ${USER}
 #
-# copy file to /usr/local/etc/rc.d/configurator 
-# chmod +x /usr/local/etc/rc.d/configurator
+# configurator_venv: Directory where hass-configurator virtualenv is located.
+#       Default:  "/usr/local/share/configurator"
+#       Change:   `sysrc configurator_venv="/srv/configurator"`
+#       UnChange: `sysrc -x configurator_venv`
 #
-# sysrc configurator_enable=yes                      # to enable
-# sysrc configurator_config ="~/.configurator.conf"  # to change
-# service configurator start                         # to start
+# configurator_config:	Full path to hass-configurator settings.conf.
+#       Default:  "/home/${USER}/configurator.conf"
+#       Change:   'sysrc configurator_config="/home/hass/configurator.conf"`
+#       UnChange: `sysrc -x configurator_config`
+#
+# -------------------------------------------------------
+# Copy this file to '/usr/local/etc/rc.d/configurator' 
+# `chmod +x /usr/local/etc/rc.d/configurator`
+# `sysrc configurator_enable=YES`
+# `service configurator start`
+# ---------------------------------------------
 
 . /etc/rc.subr
 name=configurator
@@ -32,39 +40,63 @@ pidfile_child="/var/run/${name}.pid"
 pidfile="/var/run/${name}_daemon.pid"
 logfile="/var/log/${name}_daemon.log"
 
-load_rc_config ${name}
 : ${configurator_enable:="NO"}
 : ${configurator_user:="hass"}
 : ${configurator_group:="hass"}
 : ${configurator_config:="/home/hass/configurator/configurator.conf"}
-: ${configurator:="/srv/configurator/configurator.py"}
+: ${configurator_venv:="/srv/configurator"}
 
 command="/usr/sbin/daemon"
+extra_commands="upgrade test"
 
-start_precmd=${name}_precmd
-configurator_precmd()
-{
-        rc_flags="-f -o ${logfile} -P ${pidfile} -p ${pidfile_child} /usr/local/bin/python3.6 ${configurator} ${configurator_config} ${rc_flags}"
-        
-    if [ ! -e "${pidfile_child}" ]; then
-            install -g ${configurator_group} -o ${configurator_user} -- /dev/null "${pidfile_child}";
-    fi
-
-    if [ ! -e "${pidfile}" ]; then
-            install -g ${configurator_group} -o ${configurator_user} -- /dev/null "${pidfile}";
-    fi
- 
-    if [ ! -e "${logfile}" ]; then
-        install -g ${configurator_group} -o ${configurator_user} -- /dev/null "${logfile}";
-    fi
- 
+start_precmd="${name}_precmd"
+configurator_precmd() {
+    rc_flags="-f -o ${logfile} -P ${pidfile} -p ${pidfile_child} ${configurator_venv}/bin/hass-configurator ${configurator_config} ${rc_flags}"
+    [ ! -e "${pidfile_child}" ] && install -g ${configurator_group} -o ${configurator_user} -- /dev/null "${pidfile_child}"
+    [ ! -e "${pidfile}" ] && install -g ${configurator_group} -o ${configurator_user} -- /dev/null "${pidfile}"
+    [ -e "${logfile}" ] && rm -f -- "${logfile}"
+    install -g ${configurator_group} -o ${configurator_user} -- /dev/null "${logfile}"
 }
 
-stop_postcmd=${name}_postcmd
-configurator_postcmd()
-{
+stop_postcmd="${name}_postcmd"
+configurator_postcmd() {
     rm -f -- "${pidfile}"
     rm -f -- "${pidfile_child}"
 }
 
+upgrade_cmd="${name}_upgrade"
+configurator_upgrade() {
+    service ${name} stop
+    su ${configurator_user} -c '
+      source ${1}/bin/activate || exit 1
+      pip3 install --upgrade hass-configurator
+      deactivate
+    ' _ ${configurator_venv} || exit 1
+    [ $? == 0 ] && service ${name} start
+}
+
+test_cmd="${name}_test"
+configurator_test() {
+    ## This function servers as a simple test command.
+    echo "TEST FUNCTION"
+
+    ## return 1 if "${configurator_venv}" does not exist
+    [ ! -d "${configurator_venv}" ] && echo -e " NO DIRECTORY: ${configurator_venv}\n" && exit 1
+
+    ## Switch users / activate virtualenv / run a command
+    su "${configurator_user}" -c '
+      source ${@}/bin/activate || exit 2
+      echo " $(python --version)" || exit 3
+      echo " Hass Configurator $(pip3 show hass-configurator | grep Version | cut -d" " -f2)" || exit 4
+      deactivate
+    ' _ ${configurator_venv} || exit 1
+
+    local e=$?
+    ## Do something based on the value of e
+    [ $e == 2 ] && echo -e "Failed to activate virtualenv:\n ${configurator_venv}" || exit
+    [ $e == 3 ] && echo -e "Failed to get python version" || exit
+    [ $e == 4 ] && echo -e "${name} is not installed" || exit
+}
+
+load_rc_config ${name}
 run_rc_command "$1"
diff --git a/overlay/usr/local/etc/rc.d/homeassistant b/overlay/usr/local/etc/rc.d/homeassistant
--- a/overlay/usr/local/etc/rc.d/homeassistant
+++ b/overlay/usr/local/etc/rc.d/homeassistant
@@ -1,28 +1,36 @@
 #!/bin/sh
-
+#
 # PROVIDE: homeassistant
 # REQUIRE: LOGIN
 # KEYWORD: shutdown
 #
-# homeassistant_enable:	Set to YES to enable the homeassistant service.
-#			Default: NO
-# homeassistant_user:	The user account used to run the homeassistant daemon.
-#			This is optional, however do not specifically set this to an
-#			empty string as this will cause the daemon to run as root.
-#			Default: USER_NAME
-# homeassistant_group:	The group account used to run the homeassistant daemon.
-#			This is optional, however do not specifically set this to an
-#			empty string as this will cause the daemon to run with group wheel.
-#			Default: USER_GROUP
-# homeassistant_config_dir:	Directory where homeassistant config is located.
-#			Default: ~/homeassistant
+# homeassistant_enable: Set to YES to enable the homeassistant service.
+#		Default: NO
+# homeassistant_user: The user account used to run the homeassistant daemon.
+#		This is optional, however do not specifically set this to an
+#		empty string as this will cause the daemon to run as root.
+#		Default: hass
+# homeassistant_group: The group account used to run the homeassistant daemon.
+#		This is optional, however do not specifically set this to an
+#		empty string as this will cause the daemon to run with group wheel.
+#		Default: hass
 #
-# copy file to /usr/local/etc/rc.d/homeassistant 
-# chmod +x /usr/local/etc/rc.d/homeassistant
+# homeassistant_venv: Directory where homeassistant virtualenv is located.
+#       Default:  "/usr/local/share/homeassistant"
+#       Change:   `sysrc homeassistant_venv="/srv/homeassistant"`
+#       UnChange: `sysrc -x homeassistant_venv`
 #
-# sysrc homeassistant_enable=yes                        # to enable
-# sysrc homeassistant_config_dir="~/homeassistant"      # to change
-# service homeassistant start                           # to start
+# homeassistant_config_dir: Directory where homeassistant config is located.
+#       Default:  "/home/homeassistant/.homeassistant"
+#       Change:   `sysrc homeassistant_config_dir="/home/hass/homeassistant"`
+#       UnChange: `sysrc -x homeassistant_config_dir`
+
+# -------------------------------------------------------
+# Copy this file to '/usr/local/etc/rc.d/homeassistant' 
+# `chmod +x /usr/local/etc/rc.d/homeassistant`
+# `sysrc homeassistant_enable=yes`
+# `service homeassistant start`
+# -------------------------------------------------------
 
 . /etc/rc.subr
 name=homeassistant
@@ -32,42 +40,86 @@ pidfile_child="/var/run/${name}.pid"
 pidfile="/var/run/${name}_daemon.pid"
 logfile="/var/log/${name}_daemon.log"
 
-load_rc_config ${name}
 : ${homeassistant_enable:="NO"}
 : ${homeassistant_user:="hass"}
 : ${homeassistant_group:="hass"}
 : ${homeassistant_config_dir:="/home/hass/homeassistant"}
+: ${homeassistant_venv:="/srv/homeassistant"}
 
 command="/usr/sbin/daemon"
+extra_commands="check_config restart test upgrade"
 
 start_precmd=${name}_precmd
-homeassistant_precmd()
-{
-    rc_flags="-f -o ${logfile} -P ${pidfile} -p ${pidfile_child} /srv/homeassistant/bin/hass --config ${homeassistant_config_dir} ${rc_flags}"
-    
-    if [ ! -e "${pidfile_child}" ]; then
-            install -g ${homeassistant_group} -o ${homeassistant_user} -- /dev/null "${pidfile_child}";
-    fi
-
-    if [ ! -e "${pidfile}" ]; then
-            install -g ${homeassistant_group} -o ${homeassistant_user} -- /dev/null "${pidfile}";
-    fi
-    
-    if [ -e "${logfile}" ]; then
-    	rm -f -- "${logfile}"
-    fi
-    install -g ${homeassistant_group} -o ${homeassistant_user} -- /dev/null "${logfile}";
-    
+homeassistant_precmd() {
+    rc_flags="-f -o ${logfile} -P ${pidfile} -p ${pidfile_child} ${homeassistant_venv}/bin/hass --config ${homeassistant_config_dir} ${rc_flags}"
+    [ ! -e "${pidfile_child}" ] && install -g ${homeassistant_group} -o ${homeassistant_user} -- /dev/null "${pidfile_child}"
+    [ ! -e "${pidfile}" ] && install -g ${homeassistant_group} -o ${homeassistant_user} -- /dev/null "${pidfile}"
+    [ -e "${logfile}" ] && rm -f -- "${logfile}"
+    install -g ${homeassistant_group} -o ${homeassistant_user} -- /dev/null "${logfile}"
     if [ ! -d "${homeassistant_config_dir}" ]; then
-        install -d -g ${homeassistant_group} -o ${homeassistant_user} -m 775 -- "${homeassistant_config_dir}"
+      install -d -g ${homeassistant_group} -o ${homeassistant_user} -m 775 -- "${homeassistant_config_dir}"
     fi
 }
 
 stop_postcmd=${name}_postcmd
-homeassistant_postcmd()
-{
+homeassistant_postcmd() {
     rm -f -- "${pidfile}"
     rm -f -- "${pidfile_child}"
 }
 
+upgrade_cmd="${name}_upgrade"
+homeassistant_upgrade() {
+    service ${name} stop
+    su ${homeassistant_user} -c '
+      source ${@}/bin/activate || exit 1
+      pip3 install --upgrade homeassistant
+      deactivate
+    ' _ ${homeassistant_venv} || exit 1
+    [ $? == 0 ] && homeassistant_check_config && service ${name} start
+}
+
+check_config_cmd="${name}_check_config"
+homeassistant_check_config() {
+    [ ! -e "${homeassistant_config_dir}/configuration.yaml" ] && return 0
+    echo "Performing check on Home Assistant configuration:"
+    #eval "${homeassistant_venv}/bin/hass --config ${homeassistant_config_dir} --script check_config"
+    su ${homeassistant_user} -c '
+      source ${1}/bin/activate || exit 1
+      hass --config ${2} --script check_config || exit 2
+      deactivate
+    ' _ ${homeassistant_venv} ${homeassistant_config_dir}
+}
+
+restart_cmd="${name}_restart"
+homeassistant_restart() {
+    homeassistant_check_config || exit 1
+    echo "Restarting Home Assistant"
+    service ${name} stop
+    service ${name} start
+}
+
+test_cmd="${name}_test"
+homeassistant_test() {
+    ## This function servers as a simple test command.
+    echo "TEST FUNCTION"
+
+    ## return 1 if "${homeassistant_venv}" does not exist
+    [ ! -d "${homeassistant_venv}" ] && echo -e " NO DIRECTORY: ${homeassistant_venv}\n" && exit 1
+
+    ## Switch users / activate virtualenv / run a command
+    su "${homeassistant_user}" -c '
+      source ${1}/bin/activate || exit 2
+      echo " $(python --version)" || exit 3
+      echo " Home Assistant $(pip3 show homeassistant | grep Version | cut -d" " -f2)" || exit 4
+      deactivate
+    ' _ ${homeassistant_venv} || exit 1
+
+    local e=$?
+    ## Do something based on the value of e
+    [ $e == 2 ] && echo -e "Failed to activate virtualenv:\n ${homeassistant_venv}" || exit
+    [ $e == 3 ] && echo -e "Failed to get python version" || exit
+    [ $e == 4 ] && echo -e "${name} is not installed" || exit
+}
+
+load_rc_config ${name}
 run_rc_command "$1"
