refactor part 2 - install - install_cmd is should only be used for pip install - install_hacs is now a separate function - updated reinstall_cmd

diff --git a/overlay/usr/local/etc/rc.d/homeassistant b/overlay/usr/local/etc/rc.d/homeassistant
--- a/overlay/usr/local/etc/rc.d/homeassistant
+++ b/overlay/usr/local/etc/rc.d/homeassistant
@@ -235,7 +235,7 @@ upgrade_cmd="${name}_upgrade"
 homeassistant_upgrade() {
   homeassistant_precmd
   run_rc_command stop 2>/dev/null ; local _rcstop_=${?}
-  run_rc_command install --upgrade "${name}"
+  homeassistant_install --upgrade "${name}"
   homeassistant_check_config && [ ${_rcstop_} == 0 ] && run_rc_command start
 }
 
@@ -365,39 +365,48 @@ homeassistant_config() {
     esac
 }
 
+install_hacs_cmd="${name}_install_hacs ${1} ${2}"
+homeassistant_install_hacs() {
+  [ "${1}" == "install_hacs" ] && shift
+  local _custom_components_ _hacs_ _hacs_zip_
+  _custom_components_="${1:-"${homeassistant_config_dir}"}/custom_components"
+  _hacs_="${_custom_components_}/hacs"
+  debug "HACS install directory: ${_hacs_}"
+  if [ -d "${_hacs_}" ] && [ -n "$(ls -A "${_hacs_}")" ]; then
+    echo -e "\nHACS is already installed: ${_hacs_}" ; err 1 "expecting empty directory"
+  elif [ ! -d "${_custom_components_}" ]; then
+    install -d -g "${homeassistant_group}" -m 775 -o ${homeassistant_user} -- "${_custom_components_}"
+  fi
+  _hacs_zip_="$(mktemp -t hacs)"
+  wget -O "${_hacs_zip_}" https://github.com/hacs/integration/releases/latest/download/hacs.zip
+  unzip -qt "${_hacs_zip_}" || { rm "${_hacs_zip_}" ; err 1 "failed or invalid download" ; }
+  unzip -d "${_hacs_}" "${_hacs_zip_}" \
+  && chown -R "${homeassistant_user}":"${homeassistant_group}" "${_hacs_}" \
+  && echo -e "\nRemember to restart Home Assistant before you configure HACS\n https://hacs.xyz/docs/configuration/start \n"
+  rm "${_hacs_zip_}"
+}
 
 install_cmd="${name}_install ${*}"
 homeassistant_install() {
-  shift; local _new_ _arg_="${*:-"${name}"}"
+  [ "${1}" == "install" ] && shift
+  local _create_ _arg_
+  _arg_="${*:-"${name}"}"
   debug "install: ${_arg_}"
-  if [ "$(echo "${_arg_}" | cut -d" " -f1 | tr '[:lower:]' '[:upper:]')" == "HACS" ]; then
-    if [ -d "${HACS:="${homeassistant_config_dir}/custom_components/hacs"}" ] && [ -n "$(ls -A ${HACS})" ]; then
-      echo "${red}Is HACS already installed?${end}"; exit 1
-    fi
-    su - ${homeassistant_user} -c '
-      wget -O /var/tmp/hacs.zip https://github.com/hacs/integration/releases/latest/download/hacs.zip \
-      && unzip -d homeassistant/custom_components/hacs /var/tmp/hacs.zip
-      rm /var/tmp/hacs.zip
-    ' _ || exit 1
-    echo -e "\n${red} !! RESTART HOME ASSISTANT BEFORE THE NEXT STEP !!"
-    echo -e "${grn}     https://hacs.xyz/docs/configuration/start${end}\n"
-    exit 0
-  fi
-  if [ -d "${homeassistant_venv}" ] && [ -n "$(ls -A ${homeassistant_venv})" ]; then
-    info "found existing directory: ${homeassistant_venv}"
-    homeassistant_precmd
-  elif [ ! -d "${homeassistant_venv}" ] && [ "${_ck="$(echo "${1}" | cut -d= -f1)"}" != "${name}" ]; then
-    debug "name check: ${_ck}"
-    err 1 "${name} is not installed: ${homeassistant_venv}"
-  else
-    info "creating virtualenv: ${homeassistant_venv}"
+  if [ "${1%==*}" == "${name}" ] && { [ ! -d "${homeassistant_venv}" ] || [ -n "$(ls -A ${homeassistant_venv})" ]; }; then
+    debug "creating virtualenv: ${homeassistant_venv}"
     install -d -g "${homeassistant_group}" -m 775 -o ${homeassistant_user} -- ${homeassistant_venv} 2>/tmp/err \
     || err ${?} "$(</tmp/err)"
-    _new_="Y"
+    _create_="YES"
+  elif [ -d "${homeassistant_venv}" ]; then
+    debug "found existing directory: ${homeassistant_venv}"
+    homeassistant_precmd
+  else
+    echo "failed to install: ${_arg_}"
+    err 1 "${name} is not installed: ${homeassistant_venv}"
   fi
   # shellcheck disable=SC2016
   su ${homeassistant_user} -c '
-    if [ ${1} == "Y" ]; then
+    if [ ${1} == "YES" ]; then
       ${2} -m venv ${3}
       source ${3}/bin/activate 2>/tmp/err || exit 1
       shift 3
@@ -409,40 +418,43 @@ homeassistant_install() {
       pip install ${@}
     fi
     deactivate
-  ' _ ${_new_:-"N"} ${homeassistant_python} ${homeassistant_venv} "${_arg_}" || err ${?} "$(</tmp/err)"
+  ' _ ${_create_:-"NO"} ${homeassistant_python} ${homeassistant_venv} "${_arg_}" || err ${?} "$(</tmp/err)"
 }
 
 reinstall_cmd="${name}_reinstall ${*}"
 homeassistant_reinstall() {
-  shift; local _ck_ _rcstop_ _v_ _arg_="${*}"
+  [ "${1}" == "reinstall" ] && shift
+  local _ans1_ _ans2_ _rcstop_ _version_ _arg_
   homeassistant_precmd
-  if [ -z "${_arg_}" ]; then
-    if [ -n "${_v_:=$(cat ${homeassistant_config_dir}/.HA_VERSION 2>/dev/null)}" ] \
-    || [ -n "${_v_:=$(${homeassistant_venv}/bin/hass --version 2>/dev/null)}" ]; then
-      _arg_="${name}==${_v_}"
+  if [ "${1%==*}" == "${name}" ]; then
+    _arg_="${*}"
+  elif [ -z "${_arg_}" ]; then
+    if [ -n "${_version_:=$(cat ${homeassistant_config_dir}/.HA_VERSION 2>/dev/null)}" ]; then
+      _arg_="${name}==${_version_}"
     else
       _arg_="${name}"
     fi
-  fi
-  if [ "${_ck_="$(echo ${_arg_} | cut -d" " -f1 | cut -d= -f1)"}" != "${name}" ]; then
-    warn "this will delete the venv for \"${name}\" but you are trying to reinstall ${_ck_}"
-    warn "expecting \"${name}\" as ARG_1 -- you'll need to manually reinstall if this is intentional"
-    return 1
   else
-    echo -e "\n${orn}You are about to recreate the virtualenv:${end} ${homeassistant_venv}"
-    echo -e "${orn}The following packages will be reinstalled:${end} ${_arg_}"
+    warn "expecting ${name} to be listed first"
+    err 1 "check args: ${*}"
+  fi
+  echo -e "\n${orn}You are about to recreate the virtualenv:${end}\n  ${homeassistant_venv}\n"
+  echo -e "${orn}The following package(s) will be installed:${end}\n  ${_arg_}\n"
     read -rp " Type 'YES' to continue: " _ans1_
     [ "$(echo "${_ans1_:-"NO"}" | tr '[:lower:]' '[:upper:]')" == "YES" ] || exit
     echo -e "\n${orn}Do you want to clear the pip cache?${end}"
     read -rp " Type 'YES' to clear cache: " _ans2_
     if [ "$(echo "${_ans2_:-"NO"}" | tr '[:lower:]' '[:upper:]')" == "YES" ]; then
-    ## NOTE the iocage plugin does not have pip outside the venv ( this is intentional )
       # shellcheck disable=SC2016
       su ${homeassistant_user} -c '
         source ${1}/bin/activate 2>/tmp/err || exit
         pip cache purge
         deactivate
       ' _ ${homeassistant_venv}
+  fi; echo
+  run_rc_command stop 2>/dev/null; _rcstop_=${?}
+  cd / ; rm -r -- "${homeassistant_venv}" || err 1 "failed to remove ${homeassistant_venv}"
+  homeassistant_install ${_arg_} && [ ${_rcstop_} == 0 ] && run_rc_command start
 }
 
 info_cmd=${name}_info
