it's a trap

diff --git a/overlay/root/bin/hass-helper b/overlay/root/bin/hass-helper
--- a/overlay/root/bin/hass-helper
+++ b/overlay/root/bin/hass-helper
@@ -182,6 +182,10 @@ read_options(){
   esac
 }
 
+set_false() {
+  log_watch="N"
+}
+
 show_colors() {
 # Test function to see how colors look
   echo "${red}! ALERT !"
@@ -195,8 +199,25 @@ show_colors() {
 # ----------------------------------------------
 # Step #3: Trap CTRL+C, CTRL+Z and quit singles
 # ----------------------------------------------
-trap '' SIGINT SIGQUIT SIGTSTP
- 
+# Included from original example
+#trap '' SIGINT SIGQUIT SIGTSTP
+
+## TODO Expand using this example instead
+##      to call a function when signal is caught.
+
+# Define and use traps to clean up all temp files
+   # Trap on:  Use 'kill -l' to list all
+   # 1 = SIGHUP (Hangup of controlling terminal or death of parent)
+   # 2 = SIGINT (Interrupted by the keyboard)
+   # 3 = SIGQUIT (Quit signal from keyboard)
+   # 6 = SIGABRT (Aborted by abort(3))
+   # 9 = SIGKILL (Sent a kill command)
+
+   # Create Trap for ^\ & Others: Call Funtion CleanExit
+#   trap CleanExit 1 3 6 9
+   trap set_false 2
+
+
 # -----------------------------------
 # Step #4: Main logic - infinite loop
 # ------------------------------------
