add menu_service

diff --git a/overlay/root/bin/menu b/overlay/root/bin/menu
--- a/overlay/root/bin/menu
+++ b/overlay/root/bin/menu
@@ -4,7 +4,6 @@
 # The console menu for the TrueNAS Core Community Plugin, Home Assistant Core, is
 # just a simple menu, nothing more than a shortcut to execute basic service commands.
 
-plugin_version="5"
 main_menu="0"
 
 # ----------------------------------
@@ -60,43 +59,35 @@ show_banner_3() {
 }
 
 service_menu() {
-  local _cmd_ _commands_ _ans_ _venv_
+  ## Show a menu and run basic commands for each of the plugin's services
+  local _cmd_ _commands_ _ans_
   ## Commands that all service menus should have
   _commands_="status restart upgrade start stop test"
-  # Home Assistant Core has an extra check_config option in this menu
+  ## Home Assistant Core has an extra check_config option in it's menu
   [[ "${1}" == "homeassistant" ]] && _commands_="${_commands_} check_config"
-  ## Other services can be installed or removed depending on existing state of the venv
+  ## Optional services can be installed or removed depending on their existing state
   if [ "${1}" == "appdaemon" ] || [ "${1}" == "configurator" ]; then
-    [ -d "${_venv_:="$(sysrc -n "${1}_venv" 2>/dev/null)"}" ] \
+    [ -d "$(sysrc -n "${1}"_venv 2>/dev/null)" ] \
     && _commands_="${_commands_} remove" || _commands_="${_commands_} install"
   fi
   ## Prompt for user input and run command when provided
   PS3=""$'\n'"${blu}Select: ${end}" ; echo
-  select _cmd_ in "main menu" ${_commands_} "exit menu"; do
+  select _cmd_ in "main menu" ${_commands_} "exit"; do
     case "${_cmd_}" in
       "main menu")
         show_menu="NO" ; break
         ;;
-      "exit menu")
-        show_menu="NO" ; exit 0
+      "exit")
+        goodbye ; exit 0
         ;;
       "install")
-        install_service "${1}"
+        menu_service install "${1}"
         pause ; break
         ;;
       "remove")
-        echo -e "\n${orn} This will remove the rcvars and venv for \"${1}\": ${red}${_venv_}${end}"
-        read -rp " Type 'YES' to continue: " _ans_
-        [[ ${_ans_} == [Yy][Ee][Ss] ]] || break
-        echo
-        service "${1}" stop 2>/dev/null
-        rm -r "${_venv_}"
-        for _var_ in $(eval sysrc -ae | grep ^"${1}")
-          do
-            echo "removing rcvars for \"${_var_}\""
-            sysrc -x "${_var_}" | cut -d= -f1
-          done
-        pause ; break ;;
+        menu_service remove "${1}"
+        pause ; break
+        ;;
       "status"|"restart"|"upgrade"|"start"|"stop"|"test"|"check_config")
         service "${1}" "${_cmd_}"
         pause ; break
@@ -110,19 +101,18 @@ service_menu() {
 
 show_menu_0() {
 # clear --> moved to show_banner
-  echo " 1) Home Assistant"
-  echo " 2) Configurator"
-  echo " 3) AppDaemon"
-  echo
-  echo " 0) Exit Menu"
-  echo
+  echo " 1) Home Assistant Core"
+  echo " 2) Configurator (File Editor)"
+  echo " 3) AppDaemon + HA-Dashboard"
+  echo -e "\n 0) Exit Menu \n"
+
 }
 
-read_options(){
+read_options() {
   local choice
   echo "${blu}" ; read -rp "Select: " choice ; echo "${end}"
   case "${choice}" in
-  ## Select which service menu to load, or command to run
+   ## Select which menu to load, or command to run
     "1") # Home Assistant Core
       show_menu="YES"
       while [ ${show_menu} == "YES" ]; do
@@ -149,7 +139,7 @@ read_options(){
       install_hacs
       pause ; return
       ;;
-    ## A few more ways to exit to the console
+    ## Exit menu, returns to the jail's console
     [eE]|[eE][xX][iI][tT]|[qQ]|[cC]|[cC]|[oN][sS][oO][lL][eE]|"0")
       goodbye
       ;;
@@ -159,7 +149,7 @@ read_options(){
   esac
 }
 
-pause(){
+pause() {
   echo ; read -rp "Press ENTER to continue..." fackEnterKey
 }
 
@@ -173,27 +163,26 @@ load_colors() {
   orn=$'\e[38;5;208m'
   red=$'\e[1;31m'
   end=$'\e[0m'
-}
+} ; load_colors # Only loaded once
 
 # ----------------------------------------------
 # Step #3: Trap CTRL+C, CTRL+Z and quit singles
 # ----------------------------------------------
-#
-# Define and use traps to clean up all temp files
-# Trap on: --> Use 'kill -l' to list all
+
+## Define and use traps to clean up all temp files
+#  Trap on --- use 'kill -l' to list all
 #   1 = SIGHUP (Hangup of controlling terminal or death of parent)
 #   2 = SIGINT (Interrupted by the keyboard)
 #   3 = SIGQUIT (Quit signal from keyboard)
 #   6 = SIGABRT (Aborted by abort(3))
 #
-# Create trap for ^C & others - calls function goodbye
-  trap goodbye 1 2 3 6
+## It's a trap! goodbye
+trap goodbye 1 2 3 6
 
 # -----------------------------------
 # Step #4: Main logic - infinite loop
 # ------------------------------------
 
-load_colors # Only need to load colors once
 while true; do
   show_banner_0 && show_menu_${main_menu} && read_options
 done
